# Generated by Django 4.0.3 on 2022-03-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weathercode', models.IntegerField(choices=[(0, 'Clear'), (3, 'Partly Cloudy'), (51, 'Drizzle'), (61, 'Rain'), (80, 'Rain Showers'), (95, 'Thunderstorm'), (96, 'Thunderstorm')], default=0)),
                ('temperature', models.FloatField(default=0.0)),
                ('max_temperature', models.FloatField(default=0.0)),
                ('min_temperature', models.FloatField(default=0.0)),
                ('sunrise', models.DateTimeField(null=True)),
                ('sunset', models.DateTimeField(null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
